### ISSUE TITLE
Any wp-cli command support?

### ISSUE THREAD

**Issue by gurumark** [WPDevelopers/disable-comments#132]
Hello,
Do you plan to support wp-cli - setting options through commands?

Thank you!

**Comment by abid112** [comment]
Hi @gurumark ,

Yes, This is already on our roadmap. We have a plan to bring this **WP-CLI - Setting Option** in future version.

Thank you!

**Comment by Asif2BD** [comment]
WP-CLI support released with Final version V 2.0.0 release - https://github.com/WPDevelopers/disable-comments/releases/tag/2.0.0
Check the documentation here - https://wpdeveloper.net/docs/how-to-use-disable-comments-plugin-with-wp-cli-command-line/

**Comment by gurumark** [comment]
Thank you!
