### ISSUE TITLE
Missing 1.11.0 from GitHub Releases

### ISSUE THREAD

**Issue by garretthyder** [WPDevelopers/disable-comments#133]
Hello, it appears the latest 1.11.0 release is missing from the Github Releases;
https://github.com/WPDevelopers/disable-comments/releases

**Comment by Asif2BD** [comment]
Done - https://github.com/WPDevelopers/disable-comments/releases/tag/v1.11.0

**Comment by garretthyder** [comment]
Thanks @Asif2BD

**Comment by XhmikosR** [comment]
There's also a discrepancy in the WP Plugins versions: there's v1.10.3 which isn't present in Git.

What's up with that @Asif2BD?

**Comment by XhmikosR** [comment]
OK, I checked the diff manually, and nothing fishy seems to be going on; mostly comment changes, a couple of text domain fixes and one JS change.

That being said, I'd advise against tags mismatch, missing tags, etc. While I have no reason to believe you are doing something wrong, it's proven **multiple times** that bad things can happen when projects change hands.

It's better for everyone if there's transparency and consistency between the repo and the published plugin.

**Comment by Asif2BD** [comment]
> There's also a discrepancy in the WP Plugins versions: there's v1.10.3 which isn't present in Git.
> 
> What's up with that @Asif2BD?

Thats being done by the previous developer, seems minor readme changes for WordPress - https://d.pr/i/Ql2Og7
Link - https://github.com/WPDevelopers/disable-comments/commit/0d88b8036b75f17dfeb96d4cb6e39addd3c7d633

**Comment by Asif2BD** [comment]
> OK, I checked the diff manually, and nothing fishy seems to be going on; mostly comment changes, a couple of text domain fixes and one JS change.
> 
> That being said, I'd advise against tags mismatch, missing tags, etc. While I have no reason to believe you are doing something wrong, it's proven **multiple times** that bad things can happen when projects change hands.
> 
> It's better for everyone if there's transparency and consistency between the repo and the published plugin.

It's an OpenSource project, we took over to support and improve. I am Core Contributor and heavily involved in Core WordPress project for 16 years, and currently running a nearly 50 developers' team, I think time will present how we work towards this simple but easy plugin. 
Regards!
