### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by Log1x** [WPDevelopers/disable-comments#134]
[...really?](https://github.com/WPDevelopers/disable-comments/blob/master/includes/class-plugin-usage-tracker.php#L324-L523)

**Comment by XhmikosR** [comment]
It seems this file comes from some WPInsight SDK https://github.com/WPDevelopers/disable-comments/commit/8e830bb4a4e82d8a5cfdadf4d0c542d94fa7c3a8

https://github.com/WPDevelopers/disable-comments/blob/7ef233ebf8445263b1e06b0df36cb6f5fa907573/includes/class-plugin-usage-tracker.php#L27

Even if this looks optional from a *quick look*, they get the user email address for marketing, along with other info. That alone, is a red flag for me.

I don't see why the developers would need to add this crap in what was, a pretty straight-forward and simple plugin... Well, unless, they have different plans for this data or the plugin itself.

**Comment by rupok** [comment]
Hey @XhmikosR It's totally optional and only sends some non-sensitive data if you allow from the admin notice like PHP version, plugins etc. As it's open source code, dig it and you will find out. There's nothing to be doubtful about this.

**Comment by rupok** [comment]
> [...really?](https://github.com/WPDevelopers/disable-comments/blob/master/includes/class-plugin-usage-tracker.php#L324-L523)

No, not really!

**Comment by XhmikosR** [comment]
Let's put it the other way around:

1. why would you need this info in the first place?
2. why isn't this mentioned in the changelog?

I'd urge you to consider dropping this stuff altogether.

**Comment by Log1x** [comment]
You acquired a plugin with over a million installs and the first thing you do is flip it into a marketing tool for your existing plugin farm – so yeah, really. 

You [enabled tracking by default](https://github.com/WPDevelopers/disable-comments/blob/master/includes/class-plugin-usage-tracker.php#L74-L76) and even if you opt-out on the Wizard, you decide to go ahead and [send it anyway](https://github.com/WPDevelopers/disable-comments/blob/master/disable-comments.php#L98).

> only sends **some** non-sensitive data

It currently sends (by default, and forcefully even if opting out in the wizard):

- The current user's email address
- [The current user's country](https://github.com/WPDevelopers/disable-comments/blob/master/includes/class-plugin-usage-tracker.php#L450-L456)
- Plugin name
- Site URL
- Site Name
- Site Version
- Site Language
- Multsite Status
- PHP Version
- Charset
- The full path to the disabled comments plugin (e.g. `/home/noneofyourbusiness/public_html/wp-content/...`)
- The output of `$_SERVER['SERVER_SOFTWARE']`
- Active Plugins (current site & network)
- Inactive Plugins (current site & network)
- Current text direction (e.g. RTL)

**Comment by hackles** [comment]
Oh wow, that's super duper scummy.

I wonder if that violates any privacy laws or is compliant with GDPR, especially sending the user's email address. 🤔 

Truly horrible. I can't believe that dirty rotten people like this are so quick to betray the trust and goodwill of the community.

Disgusting.

**Comment by priyomukul** [comment]
Thanks for everything, but Mr. @Log1x, you are wrong ... 

We are not getting or taking any data in any possible way, the thing you showed, [in here.](https://github.com/WPDevelopers/disable-comments/blob/master/disable-comments.php#L98) You should check where the function is called, **FYI**: There is no direct call of this function in any possible ways, it's attached to a `wp_ajax` hooks, I think you know well when it ( ajax hook ) fires, right? 

That Ajax_Hooks fires only when the marked checkbox is selected ( Please check the code from version 2.0.0 ). ( see embedded image below ) 

![SC1v2.0.0](https://cdn-std.droplr.net/files/acc_882334/7g9YaA)

This `welcome screen you see above` is removed from the latest version, but the code is still in the plugin (which should not be there), and also which is not working at all. 

And of course, the variable name is $tracker, that doesn't mean it's tracking you without your consent.

And the list you gave that's completely right, we collect those data to improve our plugin, to know about your usage of plugins and themes if there is any issue you face with our plugin, and reached to us but somehow we are not getting that error you face. we look at your data( plugins & themes list ) to check conflict. if we don't have that we simply ask for your help to find out the issue. 

**For Your Kind Information:** The list you gave, yes we collect all those data when you click **"Sure, I'd like to help"** See below. 

![SC2v2.0.*](https://cdn-std.droplr.net/files/acc_882334/AHTFyz)

Thanks,
Keep Coding, Be Happy.

**Comment by XhmikosR** [comment]
What was the exact deal when you took over the project? Where is this info publicly available?

> we collect those data to improve our plugin, to know about your usage of plugins and themes

In that case, you could make this a textarea the user would SEND to you WHEN they contact you.

**Comment by JulienMelissas** [comment]
> * [The current user's country](https://github.com/WPDevelopers/disable-comments/blob/master/includes/class-plugin-usage-tracker.php?rgh-link-date=2020-12-05T12%3A28%3A13Z#L450-L456) (using their IP in a request to `http://ip-api.com/` – `http://` [isn't a typo](https://github.com/WPDevelopers/disable-comments/blob/master/includes/class-plugin-usage-tracker.php?rgh-link-date=2020-12-05T12%3A28%3A13Z#L451))

I would also like to point out that this _insecure_ call to the IP API is also in violation of their terms:
>Free for non-commercial use, no API key required

If using the API commercially (such as for collecting customer data "to help with support requests"), you should be using this service: https://members.ip-api.com/

**Comment by priyomukul** [comment]
> In that case, you could make this a textarea the user would SEND to you WHEN they contact you.

Yes, that's right ... we could, but it's a boring/old way to contact for support. we have our lovely support team and a better system, those who are not sharing their data through our way like below![our way](https://cdn-std.droplr.net/files/acc_882334/AHTFyz) than, they can use support ticket to share their data if they want. We have a textarea there actually. 

**And, BTW, the way we offer is the user's choice, not us.**

:) Happy Coding.

**Comment by XhmikosR** [comment]
I personally give up and I will remove this package from all client installation and stop suggesting using it.

**Comment by priyomukul** [comment]
> I would also like to point out that this insecure call to the IP API is also in violation of their terms:

`Insecure call` will be fixed, thanks for the feedback. 

> If using the API commercially (such as for collecting customer data "to help with support requests"), you should be using this service: https://members.ip-api.com/

and about the violation, I was thinking that we are using this service in an Open source project which is completely free. 
I will take a look again at their policy.

@JulienMelissas thanks for the constructive comment, this is helpful to learn.
