### ISSUE TITLE
optional or local google fonts

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [WPDevelopers/disable-comments#142]
Hi all,
i'm currently trying to get rid of external font loading for our website and replace with local fonts.
I saw that this plugin uses the "DM Sans" font from `fonts.googleapis.com`.
Is it possible to either include the font files in the plugin, or make the dependency on the font optional (like a checkbox or smth. in the settings)?

In case this is not feasible i can always just comment out the import line in the stylesheet. I would have to do that after every update of the plugin though.

Thank you for offering this plugin for free :)

**Comment by TheGreatRefrigerator** [comment]
As a follow up, it's pretty easy to just download the fonts from https://fonts.google.com/
and convert them with https://transfonter.org/.
Not sure how much that changes in plugin size or wether that is an issue.

**Comment by abid112** [comment]
Hi @TheGreatRefrigerator ,

I've just talked with our dev team. Actually, if we provide these external fonts in the plugin bundle, this will be an issue for the size. So we're using CDN.

Hope you understand.

**Comment by TheGreatRefrigerator** [comment]
@abid112 no worries,

could you also give a statement regarding making the font optional? Not sure if that is rather trivial to do or not.
If that's also not an option, we can close this.

**Comment by abid112** [comment]
Hi @TheGreatRefrigerator ,

I've actually tried to dequeue the style.css file from the plugin theme functions.php file so that you can create a new style.css file without that font-face and enqueue from the child theme.

However, It seems I can't do it for the priority even if I set the higher priority for that. So I'm sorry to inform you that currently, we don't have any workaround to ignore this actually.

Hope you understand.
Thank you!

**Comment by TheGreatRefrigerator** [comment]
No problem, @abid112 thank's for trying!
I also don't have the time right now to try this out and do a PR, but maybe at some point.
Feel free to close this issue or tag it for "help wanted" as you see fit.

Best regards

**Comment by abid112** [comment]
Hi @TheGreatRefrigerator ,

How are you today? Good news for you!
You don't need to remove the CDN from `style.css` file anymore after every update. 

We've included the fonts locally now in the latest version of **Disable Comments v2.4.1** 

Cheers and Have a good day!
