### ISSUE TITLE
Undefined array key "HTTP_REFERER" in Disable_Comments::is_network_admin()

### ISSUE THREAD

**Issue by lakrisgubben** [WPDevelopers/disable-comments#144]
Hi,

first of all thanks for a great plugin! :) We've been getting some php warnings (E_WARNING: Undefined array key "HTTP_REFERER") from the `$_SERVER['HTTP_REFERER']` check here https://github.com/WPDevelopers/disable-comments/blob/master/disable-comments.php#L114. That variable can be empty under certain circumstances, [quoting the php.net documentation:](https://www.php.net/manual/en/reserved.variables.server.php): "Not all user agents will set this, and some provide the ability to modify HTTP_REFERER as a feature. In short, it cannot really be trusted.".

I think the easiest fix for this is to add an isset check before trying to get the value from `$_SERVER['HTTP_REFERER']`. Happy to make a PR if you'd like. :)

**Comment by abid112** [comment]
Hi @lakrisgubben ,

Thanks for pointing this out. We really appreciate it.
I will talk to our dev team lead Sunday and check this all around our codebase. We will definitely fix this and release a new update for this. 

Cheers!

**Comment by lakrisgubben** [comment]
Hey @abid112, that's great to hear. Thanks for the quick reply! :)

have a nice weekend!

**Comment by abid112** [comment]
Hi @lakrisgubben , 

Hope you're doing good today.
As I promised, I've communicated with our team and fixed this one of our branches. Could you please test this branch: https://github.com/WPDevelopers/disable-comments/tree/alim-dev

Here you can check the commit as well: https://github.com/WPDevelopers/disable-comments/commit/cd96720abd861a0b9ecf9cb3027940de9a2f084d

Let me know how it goes. We will prepare a new release for this.
Cheers!

**Comment by abid112** [comment]
Hi @lakrisgubben , we've pushed on `master` branch and released a new update with this fix as well.
Everything should be fine now.

If you don't mind me asking, could you do me a favor, and spend 30-sec to review us following this link: https://wordpress.org/support/plugin/disable-comments/reviews/#new-post

That would be awesome!
Have a good day!

**Comment by lakrisgubben** [comment]
thank you very much for the quick fix @abid112, much appreciated! Have a great day. :)
