### ISSUE TITLE
Please stop showing notice

### ISSUE THREAD

**Issue by Beee4life** [WPDevelopers/disable-comments#145]
Every time I activate a plugin, a notice from your plugin pops up if I want to contribute. I click to hide it every time but after every plugin activation there it is again...

**Comment by abid112** [comment]
Hi @Beee4life , 

We could not reproduce this issue actually. If you press "**No Thanks**", this error won't show you again actually even if you deactivate and activate the plugin. Please have a look at this video: https://d.pr/v/XMtZ3w

Could you please tell me in which case you're facing this issue? Could you please tell me the steps so that I can reproduce and assist you with this?

Thank you!

**Comment by Beee4life** [comment]
It shows again, when I activate another plugin... not yours... so your plugin is active... i click no thanks...

activate another plugin and there is the message again...

**Comment by abid112** [comment]
Hi @Beee4life , 

I've tried to reproduce this issue by following your steps. However, could not able to reproduce. Have a look at this: https://d.pr/v/rGIwUN

Could you please create a support ticket here with temporary admin access from here: https://wpdeveloper.com/support/new-ticket/

We will deeply check this issue on your website and assist you with this don't worry.
Thank you!

**Comment by Beee4life** [comment]
I tried to recreate it in a sandbox env and there it wasn't triggered, but I work for an agency so I work on dosens of sites. Don't know which one it came up in.  

Would need to re-check first.

> Could you please create a support ticket here with temporary admin access
Aside from not knowing which site it was, sorry but no. I don't know you, not going to give someone on a forum a login.

Will check where it occurred...

**Comment by Beee4life** [comment]
Screencast: [https://recordit.co/HBLpkFVWK8](https://recordit.co/HBLpkFVWK8)

**Comment by Beee4life** [comment]
IF something is causing, I suspect it's [this](https://github.com/Beee4life/b3-onboarding/blob/master/B3Onboarding.php#L1238).

**Comment by alimuzzaman** [comment]
@Beee4life I have made a pull request with the fix.
https://github.com/Beee4life/b3-onboarding/pull/22

**Comment by Beee4life** [comment]
Thank you, i will look at it, but preparing a big release so if that's the fix, i'll be most likely adding it instead of merging it.

**Comment by Beee4life** [comment]
@alimuzzaman your hunch was correct. I have changed it in my branch and will be in next release. Thank you.
